### ISSUE TITLE
ReferenceError: weakly-referenced object no longer exists on resize after Init Dark or Light Mode

### ISSUE THREAD

**Issue by CodexLink** [CodexLink/EXDI-SMLV#1]
I can't find the issue, but I felt that it was caused by the snack bar, will conquer this problem soon if possible. Not tried of resizing without snack bar but that would be appreciatable if that would only be the one that could cause this weak reference object.
Here is the log anyway:
` Traceback (most recent call last):
   File "c:\Users\janja\.vscode\extensions\ms-python.python-2019.2.5433\pythonFiles\ptvsd_launcher.py", line 45, in <module>
     main(ptvsdArgs)
   File "c:\Users\janja\.vscode\extensions\ms-python.python-2019.2.5433\pythonFiles\lib\python\ptvsd\__main__.py", line 357, in main
     run()
   File "c:\Users\janja\.vscode\extensions\ms-python.python-2019.2.5433\pythonFiles\lib\python\ptvsd\__main__.py", line 257, in run_file
     runpy.run_path(target, run_name='__main__')
   File "C:\Users\janja\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 263, in run_path
     pkg_name=pkg_name, script_name=fname)
   File "C:\Users\janja\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 96, in _run_module_code
     mod_name, mod_spec, pkg_name, script_name)
   File "C:\Users\janja\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "e:\A Development That No One Knows\Github\InventoryEditor-Data_List_Simplier_AEMB\Main_Application_Target\InventoryMainScript_IDLS_AEMB.py", line 393, in <module>
     MD_InventoryEXI_SMV_GUI().run()
   File "C:\Users\janja\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\app.py", line 826, in run
     runTouchApp()
   File "C:\Users\janja\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Users\janja\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\window\window_sdl2.py", line 727, in mainloop
     self._mainloop()
   File "C:\Users\janja\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\window\window_sdl2.py", line 562, in _mainloop
     self._size = self._win.window_size
   File "kivy\properties.pyx", line 483, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 817, in kivy.properties.ListProperty.set
   File "kivy\properties.pyx", line 524, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 579, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "kivy\properties.pyx", line 1449, in kivy.properties.AliasProperty.trigger_change
   File "kivy\properties.pyx", line 1455, in kivy.properties.AliasProperty.trigger_change
   File "kivy\properties.pyx", line 579, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1096, in kivy._event.EventObservers._dispatch
   File "C:\Users\janja\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\lang\builder.py", line 73, in call_fn
     e_value = eval(value, idmap)
   File "<string>", line 25, in <module>
   File "kivy\weakproxy.pyx", line 30, in kivy.weakproxy.WeakProxy.__getattr__
   File "kivy\weakproxy.pyx", line 26, in kivy.weakproxy.WeakProxy.__ref__
 ReferenceError: weakly-referenced object no longer exists`

**Comment by CodexLink** [comment]
There is some parts where, when the snackbar wasn't called during night / light mode activation, the program doesnt crash. Therefore not solved when it has snackbar but has been solve without it. Issue Closed...
